# Generated by Django 3.2.25 on 2025-03-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_professor_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='code',
        ),
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
