# Generated by Django 3.2.25 on 2025-03-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20250306_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='module',
        ),
        migrations.AddField(
            model_name='rating',
            name='module_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.moduleinstance'),
        ),
    ]
